### ISSUE TITLE
Does not find local files when they are requested with query parameters

### ISSUE THREAD

**Issue by hytromo** [kinchanmaemo/standalone-html#2]
Thanks for this tool, I found it very useful!

A little issue I had was the following:

If the html file had something like this:
`<img src="/path/to/file.jpg?token=1234>` then the script tried to look for `/path/to/file.jpg?token=1234` (obviously file not found), and not `/path/to/file.jpg`.

I fixed it for myself by hacking around the code but nothing worthy of a pull request!

Thanks!

**Comment by kinchanmaemo** [comment]
Hi and thank you for your feedback! 

I modified the source code to avoid this error but I don't have a file that allows me to reproduce this error. Let me know if it works.
